apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
  labels:
    app: meungnix
spec:
  replicas: 3
  selector:
    ## procura pods com o label app: meungnix
    matchLabels:
      app: meungnix
  template:
    metadata:
      labels:
        app: meungnix
    spec:
      containers:
        - name: webserver
          image: ngnix:1.14.2
          env:
            - name: MINHA_VAR
              valueFrom:
                configMapKeyRef:
                  name: ambiente
                  key: minha_var
          ports:
            - containerPort: 80


